# Generated by Django 6.1.1 on 2026-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.PositiveIntegerField()),
                ('dept', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField()),
            ],
        ),
    ]
